#!/bin/bash
# This file is part of the https://gist.github.com/Maxximo88
# Inspired by the beautiful work of https://github.com/LionSec/katoolin/
# Copyright (c) 2017 Carofano Massimo Antonio
# 
# This program is free software: you can redistribute it and/or modify  
# it under the terms of the GNU General Public License as published by  
# the Free Software Foundation, version 3.
#
# This program is distributed in the hope that it will be useful, but 
# WITHOUT ANY WARRANTY; without even the implied warranty of 
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU 
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License 
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#

echo -e "\e[1;34m=====================================\e[0m"
echo -e "\e[1;34mVerifico la tua distribuzione Linux..\e[0m"
echo -e "\e[1;34m=====================================\e[0m"
DISTRO=$(lsb_release -i | cut -f 2-)
if [ $DISTRO == "Deepin" ]; then
	echo "Ok stai usando $DISTRO, procediamo.."
	echo ''
else
	echo -e "\e[1;31mQuesto script non è compatibile con la tua distribuzione Linux ($DISTRO)\e[0m"
	exit
fi

echo 'Ciao, questo script è utile per installare tutti i tool di Kali Linux su Deepin.'
echo -e "\e[1;31mIo non mi assumo alcuna responsabilità per l'utilizzo del software in questione..\e[0m"
echo 'Nel caso tu voglia installare tutto, per prima cosa aggiungi i Repo di Kali, successivamente seleziona la voce "Installa tutto"'
PS3='Seleziona il comando desiderato: '
options=("Aggiungi i Repo di Kali Linux" "Information Gathering" "Vulnerability Analysis" "Wireless Attacks" "Web Applications" "Sniffing & Spoofing" "Maintaining Access" "Reporting Tools" "Exploitation Tools" "Forensics Tools" "Stress Testing" "Password Attacks" "Reverse Engineering" "Hardware Hacking" "Extra" "Installa tutto" "Ripristina il Source.List col Mirror originale" "Termina")
select opt in "${options[@]}"
do
	case $opt in
		"Aggiungi i Repo di Kali Linux")
			echo ''
			echo -e "\e[1;31mOra modificherò il tuo Source.List aggiungendo i repo di Kali, ovviamente una copia del file Source.list verrà depositata nella medesima cartella in cui è presente questo script\e[0m"
			echo ''
			cd $HOME &
			sudo cp /etc/apt/sources.list backup.sources.list
			sudo bash -c 'cat << EOF > /etc/apt/sources.list
# Generated by deepin-installer
#deb [by-hash=force] http://packages.deepin.com/deepin lion main contrib non-free
#deb-src http://packages.deepin.com/deepin lion main contrib non-free
##########################################################################################
deb http://http.kali.org/kali kali-rolling main contrib non-free
EOF'
			sudo apt update
			echo ''
			echo 'Beh, possiamo proseguire!'
			echo -e "\e[1;31mTi ricordo le opzioni: 1.Aggiungi i Repo di Kali Linux; 2.Information Gathering; 3.Vulnerability Analysis; 4.Wireless Attacks; 5.Web Applications; 6.Sniffing & Spoofing; 7.Maintaining Access; 8.Reporting Tools; 9.Exploitation Tools; 10.Forensics Tools; 11.Stress Testing; 12.Password Attack; 13.Reverse Engineering; 14.Hardware Hacking; 15.Extra; 16.Installa tutto; 17.Ripristina il Source.List col Mirror originale; 18.Termina\e[0m"
			;;
		"Information Gathering")
			sudo apt install -y acccheck ace-voip amap automater braa casefile cdpsnarf cisco-torch cookie-cadger copy-router-config dmitry dnmap dnsenum dnsmap dnsrecon dnstracer dnswalk dotdotpwn enum4linux enumiax exploitdb fierce firewalk fragroute fragrouter ghost-phisher golismero goofile lbd maltego-teeth masscan metagoofil miranda nmap p0f parsero recon-ng set smtp-user-enum snmpcheck sslcaudit sslsplit sslstrip sslyze thc-ipv6 theharvester tlssled twofi urlcrazy wireshark wol-e xplico ismtp intrace hping3 && wget http://www.morningstarsecurity.com/downloads/bing-ip2hosts-0.4.tar.gz && tar -xzvf bing-ip2hosts-0.4.tar.gz && cp bing-ip2hosts-0.4/bing-ip2hosts /usr/local/bin/
			echo ''
			echo 'Ok, per Information Gathering sei a posto, proseguiamo!'
			echo -e "\e[1;31mTi ricordo le opzioni: 1.Aggiungi i Repo di Kali Linux; 2.Information Gathering; 3.Vulnerability Analysis; 4.Wireless Attacks; 5.Web Applications; 6.Sniffing & Spoofing; 7.Maintaining Access; 8.Reporting Tools; 9.Exploitation Tools; 10.Forensics Tools; 11.Stress Testing; 12.Password Attack; 13.Reverse Engineering; 14.Hardware Hacking; 15.Extra; 16.Installa tutto; 17.Ripristina il Source.List col Mirror originale; 18.Termina\e[0m"
		;;
		"Vulnerability Analysis")
			sudo apt install -y bbqsql bed cisco-auditing-tool cisco-global-exploiter cisco-ocs cisco-torch copy-router-config doona dotdotpwn greenbone-security-assistant hexorbase jsql lynis nmap ohrwurm openvas-cli openvas-manager openvas-scanner oscanner powerfuzzer sfuzz sidguesser siparmyknife sqlmap sqlninja sqlsus thc-ipv6 tnscmd10g unix-privesc-check yersinia
			echo ''
			echo 'Installazione dei pacchetti per la Vulnerability Analysis completata, proseguiamo!'
			echo -e "\e[1;31mTi ricordo le opzioni: 1.Aggiungi i Repo di Kali Linux; 2.Information Gathering; 3.Vulnerability Analysis; 4.Wireless Attacks; 5.Web Applications; 6.Sniffing & Spoofing; 7.Maintaining Access; 8.Reporting Tools; 9.Exploitation Tools; 10.Forensics Tools; 11.Stress Testing; 12.Password Attack; 13.Reverse Engineering; 14.Hardware Hacking; 15.Extra; 16.Installa tutto; 17.Ripristina il Source.List col Mirror originale; 18.Termina\e[0m"
		;;
		"Wireless Attacks")
			sudo apt install -y aircrack-ng asleap bluelog blueranger bluesnarfer bully cowpatty crackle eapmd5pass fern-wifi-cracker ghost-phisher giskismet gqrx kalibrate-rtl killerbee kismet mdk3 mfcuk mfoc mfterm multimon-ng pixiewps reaver redfang spooftooph wifi-honey wifitap wifite
			echo ''
			echo 'Ed ora hai anche i tool per Wireless Attacks, proseguiamo!'
			echo -e "\e[1;31mTi ricordo le opzioni: 1.Aggiungi i Repo di Kali Linux; 2.Information Gathering; 3.Vulnerability Analysis; 4.Wireless Attacks; 5.Web Applications; 6.Sniffing & Spoofing; 7.Maintaining Access; 8.Reporting Tools; 9.Exploitation Tools; 10.Forensics Tools; 11.Stress Testing; 12.Password Attack; 13.Reverse Engineering; 14.Hardware Hacking; 15.Extra; 16.Installa tutto; 17.Ripristina il Source.List col Mirror originale; 18.Termina\e[0m"
		;;
		"Web Applications")
			sudo apt install -y apache-users arachni bbqsql blindelephant burpsuite cutycapt davtest deblaze dirb dirbuster fimap funkload grabber jboss-autopwn joomscan jsql maltego-teeth padbuster paros parsero plecost powerfuzzer proxystrike recon-ng skipfish sqlmap sqlninja sqlsus ua-tester uniscan vega w3af webscarab websploit wfuzz wpscan xsser zaproxy
			echo ''
			echo 'Installazione pacchetti Web Applications completata, proseguiamo!'
			echo -e "\e[1;31mTi ricordo le opzioni: 1.Aggiungi i Repo di Kali Linux; 2.Information Gathering; 3.Vulnerability Analysis; 4.Wireless Attacks; 5.Web Applications; 6.Sniffing & Spoofing; 7.Maintaining Access; 8.Reporting Tools; 9.Exploitation Tools; 10.Forensics Tools; 11.Stress Testing; 12.Password Attack; 13.Reverse Engineering; 14.Hardware Hacking; 15.Extra; 16.Installa tutto; 17.Ripristina il Source.List col Mirror originale; 18.Termina\e[0m"
		;;
		"Sniffing & Spoofing")
			sudo apt install -y burpsuite dnschef fiked hamster-sidejack hexinject iaxflood inviteflood ismtp mitmproxy ohrwurm protos-sip rebind responder rtpbreak rtpinsertsound rtpmixsound sctpscan siparmyknife sipp sipvicious sniffjoke sslsplit sslstrip thc-ipv6 voiphopper webscarab wifi-honey wireshark xspy yersinia zaproxy
			echo ''
			echo 'Ed anche per Sniffing & Spoofing dovresti essere a posto, proseguiamo!'
			echo -e "\e[1;31mTi ricordo le opzioni: 1.Aggiungi i Repo di Kali Linux; 2.Information Gathering; 3.Vulnerability Analysis; 4.Wireless Attacks; 5.Web Applications; 6.Sniffing & Spoofing; 7.Maintaining Access; 8.Reporting Tools; 9.Exploitation Tools; 10.Forensics Tools; 11.Stress Testing; 12.Password Attack; 13.Reverse Engineering; 14.Hardware Hacking; 15.Extra; 16.Installa tutto; 17.Ripristina il Source.List col Mirror originale; 18.Termina\e[0m"
		;;
		"Maintaining Access")
			sudo apt install -y cryptcat cymothoa dbd dns2tcp http-tunnel httptunnel intersect nishang polenum powersploit pwnat ridenum sbd u3-pwn webshells weevely
			echo ''
			echo 'Installazione pacchetti Maintaining Access completata, proseguiamo!'
			echo -e "\e[1;31mTi ricordo le opzioni: 1.Aggiungi i Repo di Kali Linux; 2.Information Gathering; 3.Vulnerability Analysis; 4.Wireless Attacks; 5.Web Applications; 6.Sniffing & Spoofing; 7.Maintaining Access; 8.Reporting Tools; 9.Exploitation Tools; 10.Forensics Tools; 11.Stress Testing; 12.Password Attack; 13.Reverse Engineering; 14.Hardware Hacking; 15.Extra; 16.Installa tutto; 17.Ripristina il Source.List col Mirror originale; 18.Termina\e[0m"
		;;
		"Reporting Tools")
			sudo apt install -y casefile cutycapt dos2unix dradis keepnote magictree metagoofil nipper-ng pipal
			echo ''
			echo 'Reporting Tools installati, proseguiamo!'
			echo -e "\e[1;31mTi ricordo le opzioni: 1.Aggiungi i Repo di Kali Linux; 2.Information Gathering; 3.Vulnerability Analysis; 4.Wireless Attacks; 5.Web Applications; 6.Sniffing & Spoofing; 7.Maintaining Access; 8.Reporting Tools; 9.Exploitation Tools; 10.Forensics Tools; 11.Stress Testing; 12.Password Attack; 13.Reverse Engineering; 14.Hardware Hacking; 15.Extra; 16.Installa tutto; 17.Ripristina il Source.List col Mirror originale; 18.Termina\e[0m"
		;;
		"Exploitation Tools")
			sudo apt install -y armitage backdoor-factory cisco-auditing-tool cisco-global-exploiter cisco-ocs cisco-torch crackle jboss-autopwn linux-exploit-suggester maltego-teeth set shellnoob sqlmap thc-ipv6 yersinia beef-xss
			echo ''
			echo 'Exploitation Tools installati, proseguiamo!'
			echo -e "\e[1;31mTi ricordo le opzioni: 1.Aggiungi i Repo di Kali Linux; 2.Information Gathering; 3.Vulnerability Analysis; 4.Wireless Attacks; 5.Web Applications; 6.Sniffing & Spoofing; 7.Maintaining Access; 8.Reporting Tools; 9.Exploitation Tools; 10.Forensics Tools; 11.Stress Testing; 12.Password Attack; 13.Reverse Engineering; 14.Hardware Hacking; 15.Extra; 16.Installa tutto; 17.Ripristina il Source.List col Mirror originale; 18.Termina\e[0m"
		;;
		"Forensics Tools")
			sudo apt install -y binwalk bulk-extractor chntpw cuckoo dc3dd ddrescue dumpzilla extundelete foremost galleta guymager iphone-backup-analyzer p0f pdf-parser pdfid pdgmail peepdf volatility xplico
			echo ''
			echo 'Forensics Tools installati, proseguiamo!'
			echo -e "\e[1;31mTi ricordo le opzioni: 1.Aggiungi i Repo di Kali Linux; 2.Information Gathering; 3.Vulnerability Analysis; 4.Wireless Attacks; 5.Web Applications; 6.Sniffing & Spoofing; 7.Maintaining Access; 8.Reporting Tools; 9.Exploitation Tools; 10.Forensics Tools; 11.Stress Testing; 12.Password Attack; 13.Reverse Engineering; 14.Hardware Hacking; 15.Extra; 16.Installa tutto; 17.Ripristina il Source.List col Mirror originale; 18.Termina\e[0m"
		;;
		"Stress Testing")
			sudo apt install -y dhcpig funkload iaxflood inviteflood ipv6-toolkit mdk3 reaver rtpflood slowhttptest t50 termineter thc-ipv6 thc-ssl-dos
			echo ''
			echo 'Tools per Stress testing installati, proseguiamo!'
			echo -e "\e[1;31mTi ricordo le opzioni: 1.Aggiungi i Repo di Kali Linux; 2.Information Gathering; 3.Vulnerability Analysis; 4.Wireless Attacks; 5.Web Applications; 6.Sniffing & Spoofing; 7.Maintaining Access; 8.Reporting Tools; 9.Exploitation Tools; 10.Forensics Tools; 11.Stress Testing; 12.Password Attack; 13.Reverse Engineering; 14.Hardware Hacking; 15.Extra; 16.Installa tutto; 17.Ripristina il Source.List col Mirror originale; 18.Termina\e[0m"
		;;
		"Password Attack")
			sudo apt install -y acccheck burpsuite cewl chntpw cisco-auditing-tool cmospwd creddump crunch findmyhash gpp-decrypt hash-identifier hexorbase john johnny keimpx maltego-teeth maskprocessor multiforcer ncrack oclgausscrack pack patator polenum rainbowcrack rcracki-mt rsmangler statsprocessor thc-pptp-bruter truecrack webscarab wordlists zaproxy
				echo ''
				echo 'Software di Password Attack installati, proseguiamo!'
				echo -e "\e[1;31mTi ricordo le opzioni: 1.Aggiungi i Repo di Kali Linux; 2.Information Gathering; 3.Vulnerability Analysis; 4.Wireless Attacks; 5.Web Applications; 6.Sniffing & Spoofing; 7.Maintaining Access; 8.Reporting Tools; 9.Exploitation Tools; 10.Forensics Tools; 11.Stress Testing; 12.Password Attack; 13.Reverse Engineering; 14.Hardware Hacking; 15.Extra; 16.Installa tutto; 17.Ripristina il Source.List col Mirror originale; 18.Termina\e[0m"
		;;
		"Reverse Engineering")
			sudo apt install -y apktool dex2jar python-diStorm3 edb-debugger jad javasnoop JD OllyDbg smali Valgrind YARA
			echo ''
			echo 'Software di Reverse Engineering installato, proseguiamo!'
			echo -e "\e[1;31mTi ricordo le opzioni: 1.Aggiungi i Repo di Kali Linux; 2.Information Gathering; 3.Vulnerability Analysis; 4.Wireless Attacks; 5.Web Applications; 6.Sniffing & Spoofing; 7.Maintaining Access; 8.Reporting Tools; 9.Exploitation Tools; 10.Forensics Tools; 11.Stress Testing; 12.Password Attack; 13.Reverse Engineering; 14.Hardware Hacking; 15.Extra; 16.Installa tutto; 17.Ripristina il Source.List col Mirror originale; 18.Termina\e[0m"
		;;
		"Hardware Hacking")
			sudo apt install -y android-sdk apktool arduino dex2jar sakis3g smali
			echo ''
			echo 'Tools di Hardware Hacking installati, proseguiamo!'
			echo -e "\e[1;31mTi ricordo le opzioni: 1.Aggiungi i Repo di Kali Linux; 2.Information Gathering; 3.Vulnerability Analysis; 4.Wireless Attacks; 5.Web Applications; 6.Sniffing & Spoofing; 7.Maintaining Access; 8.Reporting Tools; 9.Exploitation Tools; 10.Forensics Tools; 11.Stress Testing; 12.Password Attack; 13.Reverse Engineering; 14.Hardware Hacking; 15.Extra; 16.Installa tutto; 17.Ripristina il Source.List col Mirror originale; 18.Termina\e[0m"
		;;
		"Extra")
			sudo apt install -y squid3 && git clone https://github.com/LionSec/wifresti.git && cp wifresti/wifresti.py /usr/bin/wifresti && chmod +x /usr/bin/wifresti && wifresti
			echo ''
			echo 'Beh, proseguiamo!'
			echo -e "\e[1;31mTi ricordo le opzioni: 1.Aggiungi i Repo di Kali Linux; 2.Information Gathering; 3.Vulnerability Analysis; 4.Wireless Attacks; 5.Web Applications; 6.Sniffing & Spoofing; 7.Maintaining Access; 8.Reporting Tools; 9.Exploitation Tools; 10.Forensics Tools; 11.Stress Testing; 12.Password Attack; 13.Reverse Engineering; 14.Hardware Hacking; 15.Extra; 16.Installa tutto; 17.Ripristina il Source.List col Mirror originale; 18.Termina\e[0m"
		;;
		"Installa tutto")
			sudo apt install -y acccheck ace-voip amap automater braa casefile cdpsnarf cisco-torch cookie-cadger copy-router-config dmitry dnmap dnsenum dnsmap dnsrecon dnstracer dnswalk dotdotpwn enum4linux enumiax exploitdb fierce firewalk fragroute fragrouter ghost-phisher golismero goofile lbd maltego-teeth masscan metagoofil miranda nmap p0f parsero recon-ng set smtp-user-enum snmpcheck sslcaudit sslsplit sslstrip sslyze thc-ipv6 theharvester tlssled twofi urlcrazy wireshark wol-e xplico ismtp intrace hping3 bbqsql bed cisco-auditing-tool cisco-global-exploiter cisco-ocs cisco-torch copy-router-config doona dotdotpwn greenbone-security-assistant hexorbase jsql lynis nmap ohrwurm openvas-cli openvas-manager openvas-scanner oscanner powerfuzzer sfuzz sidguesser siparmyknife sqlmap sqlninja sqlsus thc-ipv6 tnscmd10g unix-privesc-check yersinia aircrack-ng asleap bluelog blueranger bluesnarfer bully cowpatty crackle eapmd5pass fern-wifi-cracker ghost-phisher giskismet gqrx kalibrate-rtl killerbee kismet mdk3 mfcuk mfoc mfterm multimon-ng pixiewps reaver redfang spooftooph wifi-honey wifitap wifite apache-users arachni bbqsql blindelephant burpsuite cutycapt davtest deblaze dirb dirbuster fimap funkload grabber jboss-autopwn joomscan jsql maltego-teeth padbuster paros parsero plecost powerfuzzer proxystrike recon-ng skipfish sqlmap sqlninja sqlsus ua-tester uniscan vega w3af webscarab websploit wfuzz wpscan xsser zaproxy burpsuite dnschef fiked hamster-sidejack hexinject iaxflood inviteflood ismtp mitmproxy ohrwurm protos-sip rebind responder rtpbreak rtpinsertsound rtpmixsound sctpscan siparmyknife sipp sipvicious sniffjoke sslsplit sslstrip thc-ipv6 voiphopper webscarab wifi-honey wireshark xspy yersinia zaproxy cryptcat cymothoa dbd dns2tcp http-tunnel httptunnel intersect nishang polenum powersploit pwnat ridenum sbd u3-pwn webshells weevely casefile cutycapt dos2unix dradis keepnote magictree metagoofil nipper-ng pipal armitage backdoor-factory cisco-auditing-tool cisco-global-exploiter cisco-ocs cisco-torch crackle jboss-autopwn linux-exploit-suggester maltego-teeth set shellnoob sqlmap thc-ipv6 yersinia beef-xss binwalk bulk-extractor chntpw cuckoo dc3dd ddrescue dumpzilla extundelete foremost galleta guymager iphone-backup-analyzer p0f pdf-parser pdfid pdgmail peepdf volatility xplico dhcpig funkload iaxflood inviteflood ipv6-toolkit mdk3 reaver rtpflood slowhttptest t50 termineter thc-ipv6 thc-ssl-dos acccheck burpsuite cewl chntpw cisco-auditing-tool cmospwd creddump crunch findmyhash gpp-decrypt hash-identifier hexorbase john johnny keimpx maltego-teeth maskprocessor multiforcer ncrack oclgausscrack pack patator polenum rainbowcrack rcracki-mt rsmangler statsprocessor thc-pptp-bruter truecrack webscarab wordlists zaproxy apktool dex2jar python-distorm3 edb-debugger jad javasnoop jd ollydbg smali valgrind yara android-sdk apktool arduino dex2jar sakis3g smali && wget http://www.morningstarsecurity.com/downloads/bing-ip2hosts-0.4.tar.gz && tar -xzvf bing-ip2hosts-0.4.tar.gz && cp bing-ip2hosts-0.4/bing-ip2hosts /usr/local/bin/
			echo ''
			echo 'Hai installato il mondo, passa agli extra e poi ripristina il Source.list prima di uscire!'
			echo -e "\e[1;31mTi ricordo le opzioni: 1.Aggiungi i Repo di Kali Linux; 2.Information Gathering; 3.Vulnerability Analysis; 4.Wireless Attacks; 5.Web Applications; 6.Sniffing & Spoofing; 7.Maintaining Access; 8.Reporting Tools; 9.Exploitation Tools; 10.Forensics Tools; 11.Stress Testing; 12.Password Attack; 13.Reverse Engineering; 14.Hardware Hacking; 15.Extra; 16.Installa tutto; 17.Ripristina il Source.List col Mirror originale; 18.Termina\e[0m"
		;;
		"Ripristina il Source.List col Mirror originale")
			echo ''
			echo -e "\e[1;31mOra ripristinerò il tuo Source.List evitando disastri di sorta\e[0m"
			echo ''
			cd $HOME &
			sudo cp /etc/apt/sources.list backup.sources.list
			sudo bash -c 'cat << EOF > /etc/apt/sources.list
# Generated by deepin-installer
deb [by-hash=force] http://packages.deepin.com/deepin lion main contrib non-free
#deb-src http://packages.deepin.com/deepin lion main contrib non-free
EOF'
			sudo apt update
			echo ''
			echo 'Beh, a questo punto abbiamo risistemato i repo!'
			echo -e "\e[1;31mTi ricordo le opzioni: 1.Aggiungi i Repo di Kali Linux; 2.Information Gathering; 3.Vulnerability Analysis; 4.Wireless Attacks; 5.Web Applications; 6.Sniffing & Spoofing; 7.Maintaining Access; 8.Reporting Tools; 9.Exploitation Tools; 10.Forensics Tools; 11.Stress Testing; 12.Password Attack; 13.Reverse Engineering; 14.Hardware Hacking; 15.Extra; 16.Installa tutto; 17.Ripristina il Source.List col Mirror originale; 18.Termina\e[0m"
		;;
		"Termina")
			echo 'Beh, spero che questo script sia stato apprezzato...Alla prossima!'
			break
		;;
		*) echo invalid option;;
	esac
done
